### ISSUE TITLE
Epic 1: Data Retrieval and Storage

### ISSUE THREAD

**Issue by mitchellnel** [mitchellnel/fin-backend#2]
## Epic

This epic is centred around the retrieval and storage of transaction and balance data from the Plaid API.

It will involve creating an AWS Lambda function that will be the actually caller of the Plaid API endpoints for transactional and balance data. This function will be scheduled to run at the end of every day, i.e. 23:59. 

The function will then POST the data to our Spring API, which will then execute the necessary logic to store the data in our MongoDB database in an appropriate schema. This will allow for easy storage and retrieval of the data, and avoids continuously calling the Plaid API. It also gives us the flexibility of possibly exporting the data to a spreadsheet in the future.

Further to this, the POST endpoint will also be access controlled, such that only the AWS Lambda function can call it.

## User Stories

- [ ] Create POST endpoint for receiving data from AWS Lambda
- [ ] Create AWS Lambda function
- [ ] Store POSTed data in MongoDB database
