### ISSUE TITLE
Epic 2: Core API Functionality

### ISSUE THREAD

**Issue by mitchellnel** [mitchellnel/fin-backend#3]
## Epic

This epic involves creating the necessary endpoints in our Spring API to allow the React web application to retrieve the transactional and balance information from the MongoDB Atlas database.

This consists of:
- a GET endpoint for transaction data in a specific range of time (`/api/transactions?start_date={start_dat}&end_date={end_date}`)
- a GET endpoint for balance data, with the option to specify a time range
- a GET endpoint to download an Excel spreadsheet of transaction data

## User Stories

- [ ] GET transaction data in a specific date range
- [ ] GET balance data
- [ ] GET Excel spreadsheet export of transaction data
